spring:
  profiles:
    active: @profileActivation@
  application:
    name: Api Gateway
  main:
    banner-mode: off
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:

    sql: off
    com.salapp.ecommerce:
      apigateway: info
      api: info
    org.springframework:
      web:  error
    root: error
---
spring:
  config:
    activate:
      on-profile: dev
