apiVersion: v1
kind: Namespace
metadata:
  name: e-commerce
  namespace: e-commerce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: e-commerce
  labels:
    name: ecommerce
spec:
  selector:
    matchLabels:
      name: ecommerce
  template:
    spec:
      containers:
        - name: product
          image: postgres
          ports:
            - containerPort: 8080
              hostPort: 8080
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: 128Mi
              cpu: "500m"



