
server:
  port: 8090
spring:
  application:
    name: user-service
  profiles:
    active: @profileActivation@
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      database: user_db
      port: 27017
      host: localhost
      auto-index-creation: true
      password: rootpass

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: user_db
      port: 27017
      host: user_mongodb
      auto-index-creation: true


