server:
  port: 8070
spring:
  application:
    name: Product Service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://product_postgres:5432/product
    username: postgres
    password: mysecretpassword
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
