name: Integration Test in QA

on:
  push:
    branches: ["development"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Clean with Maven
        run: mvn clean
      - name: Unit Test with Maven
        run: mvn clean -Pdev -B test --file pom.xml